name: UNLOCODE Data Processing

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Install other tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mdbtools csvkit

      - name: Run Makefile
        run: |
          source venv/bin/activate
          make

      - name: Clean zip files
        run: make clean

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Automated commit"
          git add data/*.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated commit"
            git push origin main
          fi
